### ISSUE TITLE
Expand Filesystem error

### ISSUE THREAD

**Issue by onur-elbirlik** [nbelakovski/WiFiPi#1]
When I successfully connect to the rpi zero w using ssh, I try to expand filesystem just like I do when I freshly install raspbian. But when the device restarts I can't connect to the hotspot (i see on the list but I can't). How do we solve that?

**Comment by nbelakovski** [comment]
Hey I see you closed the issue, did you find a solution for your problem that you might be willing to share, or was it just something overlooked? Even if it is the latter, it would be nice to know what it was, since it suggests that maybe the documentation should be updated.

**Comment by nbelakovski** [comment]
Also, super great to know it worked for you, at least the first time!

**Comment by onur-elbirlik** [comment]
Well that was my mistake, I connected really well. However I have another
problem, I have a login page in my dorm internet and I can't use vnc viewer
since I can't install the viewer without internet.I tried sharing internet
connection using cable (im using rpi zero w) however that didnt work. Do
you have any advice?

Thanks for your response.

15 Şub 2018 Per, saat 21:57 tarihinde nbelakovski <notifications@github.com>
şunu yazdı:

**Comment by nbelakovski** [comment]
Hm, that's a tough one. Could you try creating an internet hotspot from your laptop and having the pi connect to that so that you could install vnc viewer?

**Comment by onur-elbirlik** [comment]
Oh right, I didnt think that. Can I do that automatically using wpa-conf
file? Even without fresh installation?


15 Şub 2018 Per, saat 22:29 tarihinde nbelakovski <notifications@github.com>
şunu yazdı:

**Comment by nbelakovski** [comment]
If I understand you correctly, then yes I believe so, just edit /boot/wifipi-wpa-supplicant.txt and add the SSID that your laptop is broadcasting and the correct password and it should connect within a minute. You can do `tail -f /var/log/autohotspot.log` to see it try to connect. Your ssh connection will break as it takes the hotspot down to try connecting to the laptop, but you should at least be able to see it start the process.

**Comment by onur-elbirlik** [comment]
Thank you, I will try that. I'm a senior computer science student but not
so familiar with raspberry. I will be happy to contribute If I can dive
into it. Thanks again for your fast responses.

One last question, after I connect via my laptop, and install vnc viewer,
can i connect and see virtual desktop, with your wifipi hotspot with no
internet?

15 Şub 2018 Per, saat 23:38 tarihinde nbelakovski <notifications@github.com>
şunu yazdı:

**Comment by nbelakovski** [comment]
Well you'll probably have a few more steps to go since there's no desktop installed on this by default. This post should probably help you install the desktop: https://raspberrypi.stackexchange.com/questions/65848/how-do-i-upgrade-raspbian-lite-to-raspbian-pixel. I'm not familiar with vnc viewer, but I would guess that it should work on a hotspot with no internet.

The trouble is, once you start trying to connect to the dorm internet, the hotspot will go down and your vnc connection will drop. If the pi can connect to dorm internet and get an ip on the network, even without internet access, then you should be able to re-log into it and its vnc server and finish the setup. You might need to make modifications to /usr/bin/autohotspot to get it to stay connected to the dorm internet without falling back to the hotspot, but that's risky since it could end up getting stuck and not bringing the hotspot back up to allow you to recover. I can't give more advice without knowing a lot more about your network setup, so I'll leave you here, but good luck! Let us know if it works and if you have changes to recommend to the autohotspot script to make a process like this smoother, it's definitely an interesting use case.
